---
- name: test 
  hosts: all
  become: yes

  vars:
   source_file: ./myindex/index.html
   destin_file: /var/www/html

  tasks:
  - name: ping to all servers
    ping:

  - name: check linux version
    debug: var=ansible_distribution_release


  - block: #--------UBUNTU block-------

     - name: install apache2 on all servers
       apt: name=apache2 state=latest
      
     - name: enable service on boot
       service: name=apache2 enabled=yes

     - name: copy index.html on all servers
       copy: src={{source_file}} dest={{destin_file}} mode=0555
       notify: Restart apache

    when: ansible_distribution_release == "focal"


  - block: #--------DEBIAN block-------
   
     - name: install nginx server on debian
       apt: name=nginx state=latest


     - name: enable service on boot
       service: name=nginx enabled=yes

     - name: copy index.html on all servers
       copy: src={{source_file}} dest={{destin_file}} mode=0555
       notify: Restart nginx

    when: ansible_distribution_release == "buster"

     
  handlers:
  - name: Restart apache
    service: name=apache2 state=restarted    

  - name: Restart nginx
    service: name=nginx state=restarted

...
